init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

install:
  # install latest dotnet 5
  - cmd: choco install dotnet

os: Visual Studio 2019

build_script:
  - cmd: dotnet run --project ./DustyTables.Build/DustyTables.Build.fsproj

test: off
